CREATE TABLE [dbo].[TB_STORE_DELIVERYMETHODTYPE_EXCEPTION] (
    [id]                   INT      IDENTITY (1, 1) NOT NULL,
    [fk_item_id]           BIGINT   NULL,
    [fk_itemgrp_id]        BIGINT   NULL,
    [fk_store_id]          BIGINT   NOT NULL,
    [fk_deliveryMethod_id] SMALLINT NOT NULL,
    CONSTRAINT [PK_TB_STORE_DELIVERYMETHODTYPE_EXCEPTION] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_TB_STORE_DELIVERYMETHODTYPE_EXCEPTION_TB_STORE] FOREIGN KEY ([fk_store_id]) REFERENCES [dbo].[TB_STORE] ([id]),
    CONSTRAINT [FK_TB_STORE_DELIVERYMETHODTYPE_EXCEPTION_TB_STORE_DELIVERYMETHODTYPE_EXCEPTION] FOREIGN KEY ([fk_deliveryMethod_id]) REFERENCES [dbo].[TB_TYP_DELIVERY_METHOD] ([id]),
    CONSTRAINT [FK_TB_STORE_DELIVERYMETHODTYPE_EXCEPTION_TB_STORE_DELIVERYMETHODTYPE_EXCEPTION1] FOREIGN KEY ([fk_item_id]) REFERENCES [dbo].[TB_ITEM] ([id]),
    CONSTRAINT [FK_TB_STORE_DELIVERYMETHODTYPE_EXCEPTION_TB_STORE_DELIVERYMETHODTYPE_EXCEPTION2] FOREIGN KEY ([fk_itemgrp_id]) REFERENCES [dbo].[TB_TYP_ITEM_GRP] ([id])
);

GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'استثناء های تحوبل کالا ها  را در هر فروشگاه در این جدول قرار میدهیم	 ', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_STORE_DELIVERYMETHODTYPE_EXCEPTION';
